// <auto-generated />
namespace Closure2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedBranch : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedBranch));
        
        string IMigrationMetadata.Id
        {
            get { return "201410051044466_addedBranch"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
